[tox]
requires = tox>=4
uv_mode = true
env_list =
    py{313,314}-pb30-nutv
    py{310,311,312,313,314}-pb30-naa
    py{310,311,312,313}-pb213-naa
    py313-pb29-naa
    py313-pb211-naa
    py313-pb212-naa
    py313-pb213-nutv
skipsdist = true
isolated_build = true

[testenv]
description = Regenerate stubs in tests/stubs/
package = skip

setenv =
    PYTHONUNBUFFERED = 1

    pb29:  PYBIND11_BRANCH = v2.9
    pb211: PYBIND11_BRANCH = v2.11
    pb212: PYBIND11_BRANCH = v2.12
    pb213: PYBIND11_BRANCH = v2.13
    pb30: PYBIND11_BRANCH = v3.0

    naa:   NUMPY_FORMAT = numpy-array-wrap-with-annotated
    nutv:  NUMPY_FORMAT = numpy-array-use-type-var

    PROJECT_ROOT = {toxinidir}
    TESTS_ROOT = {env:PROJECT_ROOT}/tests
    STUBS_OUT = {toxinidir}/tests/stubs
    PYTHON_TAG_FILE = {envtmpdir}/python_tag.env
    CMAKE = {envbindir}/cmake

allowlist_externals =
    bash
    git

deps =
    cmeel==0.59.0
    cmeel-eigen==3.4.0.2
    numpy~=1.20; python_version < '3.13'
    numpy>=2.1,<3; python_version >= '3.13'
    pip
    scipy~=1.0
    typing_extensions>=4,<5
    pb29:  cmake==3.31.*
    pb211: cmake==3.28.3
    pb212: cmake==3.28.3
    pb213: cmake==4.2.*
    pb30: cmake==4.2.*

commands_pre =
    bash -c 'cmake="${CMAKE}" {env:TESTS_ROOT}/install-demo-module.sh'
    {envpython} -c "import os,sys; p=os.environ['PYTHON_TAG_FILE']; v=f'python-{sys.version_info.major}.{sys.version_info.minor}'; open(p,'w').write(f'PYTHON_TAG={v}\n'); print(v)"

commands =
    {envpython} -m pip install .
    bash -c 'set -a; source "{env:PYTHON_TAG_FILE}"; set +a; \
            {env:TESTS_ROOT}/check-demo-stubs-generation.sh --stubs-sub-dir "stubs/${PYTHON_TAG}/pybind11-{env:PYBIND11_BRANCH}/{env:NUMPY_FORMAT}" --{env:NUMPY_FORMAT}'

    bash {env:TESTS_ROOT}/check-demo-errors-generation.sh "pybind11-{env:PYBIND11_BRANCH}"
